server:
  port: 8080
  servlet:
    context-path: /sample
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DATABASE_SCHEMA}
        format_sql: true
        show_sql: true
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    default-schema: ${DATABASE_SCHEMA}
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#actuator:
#  url:
#    prefix: /actuator
springdoc:
  show-actuator: true
  api-docs:
    path: /sample-api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha